export const PRODUCTO_ERROR_CODES = {
  STOCK_INVALIDO: 'STOCK_INVALIDO',
  PRECIO_INVALIDO: 'PRECIO_INVALIDO',
  DISPONIBILIDAD_INVALIDA: 'DISPONIBILIDAD_INVALIDA',
  INVENTARIO_VACIO: 'INVENTARIO_VACIO',
} as const;
