export const ERROR_CODES = {
  STOCK_INVALIDO: 'STOCK_INVALIDO',
  PRECIO_INVALIDO: 'PRECIO_INVALIDO',
  TIENDA_NO_EXISTE: 'TIENDA_NO_EXISTE',
  NO_AUTORIZADO: 'NO_AUTORIZADO',
  ERROR_INTERNO: 'ERROR_INTERNO',
} as const;
