export const TIENDA_ERROR_CODES = {
  ID_TIENDA_INVALIDO: 'ID_TIENDA_INVALIDO',
  TIENDA_NO_ENCONTRADA: 'TIENDA_NO_ENCONTRADA',
  TIENDA_YA_EXISTE: 'TIENDA_YA_EXISTE',
  TIENDA_NO_EXISTE: 'TIENDA_NO_EXISTE',
  NOMBRE_INVALIDO: 'NOMBRE_INVALIDO',
  DESCRIPCION_INVALIDA:'DESCRIPCION_INVALIDA',
  DIRECCION_INVALIDA:'DIRECCION_INVALIDA',
  TELEFONO_INVALIDO: 'TELEFONO_INVALIDO'
} as const;
